name: CI
on: workflow_dispatch
jobs:
build:
runs-on: windows-latest timeout-minute: 9999
steps: - name: Download Ngrok SNSSM run:
Invoke-WebRequest https://raw.githubusercontent.com/charan2004152004/Ngrok-Exe/main/ngrok.exe -Out File ngrok.exe
Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev 69/Test Project 1/main/Files/nssm.exe -Out File nesm.exe - name: Copy NSSM & Ngrok to Windows Directory. run: 1
copy nssm.exe C:\Windows\System32
copy ngrok.exe C:\Windows\System32 - name: Connect your NGROK account
run: Ingrok.exe authtoken Env: NGROK_AUTH TOKEN env:
NGROK_AUTH_TOKEN: $1t secrets. NGROK_AUTH_TOKEN }} name: Download Important Files. run:
Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev 69/Test Project 1/main/Files/NGROK-US.bat -Out File NGROK-Us.bat Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test Project 1/main/Files/NGROK-CHECK.bat -Out File NGROR-CHECK.bat
Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test Project 1/main/Files/loop.bat -Out File loop.bat - name: Make YML file for NGROK.
run: start NGROK-US.bat name: Enable RDP Access. run:
Set-Item Property -Path HKLM: \System\CurrentControlSet\Control Terminal Server'-name "EDenyts Connections" -Value 0 Enable-Net Firewall Rule -DisplayGroup"Remote Desktop"
Set-Item Property -Path "HKLM\System\CurrentControlSet\Control Terminal Server\WinStations RDP-Top' -name "UserAuthentication" -Value 1 - name: Create Tunnel
run: 30 start ngzok name: Connect to your RDP 2core-7GB Ram. run: cmd /c NGROR-CHECK.bat name: All Done! You can close Tab now! Maximum VW time: 6h. run: cmd/c loop.bat
